apiVersion: v1
#我的k8s有哪些volume
kind: PersistentVolume
metadata:
  name: my-local-pv
spec:
  storageClassName: k8s-mysql-local-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/webook"
