apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #这里是指我 mysql 需要用的东西
  name: webook-mysql-claim
spec:
  #需要和pv中的storageClassName名称相同
  storageClassName: k8s-mysql-local-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi